on: [push]

jobs:
  aws_cdk:
    runs-on: ubuntu-latest
    steps:
    
      - name: Checkout
        uses: actions/checkout@v2

      - name: S3 Sync
        uses: ItsKarma/aws-cli@v1.70.0
        with:
          args: s3 sync --delete --acl public-read localdir/ s3://remote-bucket/
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_DEFAULT_REGION: "eu-central-1"


      - name: install npm
        run: 'sudo apt update -y && sudo apt install nodejs npm -y'

      - name: Install AWS CDK
        run: 'sudo npm install -g aws-cdk'

      - name: Install Requirements
        run: 'pip3 install -r requirements.txt'
        working-directory: aws_sonarqube_runner

      - name: CDK Synth
        run: cdk synth
        working-directory: aws_sonarqube_runner

      - name: CDK Deploy
        run: cdk deploy
        working-directory: aws_sonarqube_runner
